name: CI for testing

on:

push:

branches:

- main

jobs:

Set up and test:

    runs-on: ubuntu-latest

    name: Run ESLint and Jest

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint (Run ESLint)

    - run: npm run test (Run Jest)
